[phases.setup]
nixPkgs = [
  "nodejs_20",
  "python311Full"
]

aptPkgs = [
  "poppler-utils",
  "tesseract-ocr"
]

[phases.install]
cmds = [
  "npm ci || npm install",
  "python3 -m pip install -r requirements.txt"
]

[start]
cmd = "node server.js"